# Generated by Django 2.1.3 on 2018-12-09 20:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50, verbose_name='标题')),
                ('blog_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论量')),
                ('favor_nums', models.IntegerField(default=0, verbose_name='收藏量')),
                ('read_nums', models.IntegerField(default=0, verbose_name='阅读量')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞量')),
                ('posted_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'ordering': ['-posted_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='RandImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rand_img', models.ImageField(upload_to='random_imgs/%Y/%m', verbose_name='博客配图')),
                ('posted_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '博客配图',
                'verbose_name_plural': '博客配图',
            },
        ),
    ]
